### ISSUE TITLE
Thông tin tác giả

### ISSUE THREAD

**Issue by hieplpvip** [belivipro9x99/themis-web-interface#25]
**Câu hỏi**

Cho em hỏi tác giả project này là ai thế ạ :v Em thấy favicon trùng với web của trường em (em học Phổ thông Năng khiếu) nên hơi tò mò :v

**Comment by belivipro9x99** [comment]
Chào bạn,

Cảm ơn bạn đã quan tâm tới project này của mình!
Mình tên là Hà, hiện mình đang học tại trường THPT Lạc Long Quân, Hoà Bình.

Về phần favicon của project này trùng với web của trường bạn. Mình lấy tệp favicon này từ một dự án cũ của Nguyễn Hoàng Phú [tại đây](http://www.mediafire.com/file/s8as1dtbqas7cxj/JUDGER.zip). Mình xin lỗi nếu nó trùng với trang web của bạn.

Nếu bạn muốn, mình sẽ thay đổi favicon của dự án này trong thời gian sớm nhất!

**Comment by belivipro9x99** [comment]
Cảm ơn bạn vì đã góp ý! Mình đã thay đổi icon tại commit 9158e031f89731373d2e489179b63c021dfef27c.
