### ISSUE TITLE
Không thể xem logs làm bài trên web,

### ISSUE THREAD

**Issue by Noboroto** [belivipro9x99/themis-web-interface#28]
**Mô tả lỗi**
Tất cả các user không thể xem nhật ký làm bài của chính mình hoặc của người khác mặc dù chức năng "cho phép xem xem tệp nhật ký" và "cho phép xem tệp nhật ký của người khác" đã bật, bảng xếp hạng vẫn hiển thị đầy đủ thông tin

**Desktop**
 - Hệ điều hành: Windown 10 build 1903
 - Trình duyệt Chrome
 - Phiên bản 77.0.3865.120 (Official Build) 

**Thông tin thêm**
Phiên bản ThemisWebInterface v0.5.0

**Comment by belivipro9x99** [comment]
Chào Bạn,

Mong bạn gửi thông tin chi tiết hơn về lỗi (*thêm ảnh chụp màn hình khi lỗi*, *đính kèm tệp nhật ký bài làm* hoặc *đính kèm nhật ký của console*) để mình có thể điều tra nguyên nhân và khắc phục 
lỗi trong thời gian sớm nhất!

**Comment by belivipro9x99** [comment]
*Lỗi đã điều tra được nguyên nhân*
> Do có 1 test trong tệp nhật ký không có dữ liệu `Thời Gian Chạy`

Stack:
```
core.js?v=0.5.0:550 Uncaught (in promise) TypeError: Cannot read property 'toFixed' of undefined
    at Object.viewLog (core.js?v=0.5.0:550)
        viewLog @ core.js?v=0.5.0:550
        async function (async)
        viewLog @ core.js?v=0.5.0:523
        onclick @ (index):1
```

Hiện đang trong quá trình sửa lỗi

**Comment by belivipro9x99** [comment]
Đã sửa lỗi tại commit 74ce37f48a6ab2d8444f1526fecd69e88de52039
