### ISSUE TITLE
Lỗi font ở phiên bản mới nhất

### ISSUE THREAD

**Issue by snowynguyen** [belivipro9x99/themis-web-interface#31]
Toàn bộ các title bị chuyển thành font Times New Roman.

Cách tái lập lỗi: xóa toàn bộ bản cũ và cài đặt bản mới nhất v.0.5.2. Giao diện bị đổi font như ảnh đính kèm.

![times](https://user-images.githubusercontent.com/30857393/68544872-ead83780-03f9-11ea-9da4-edbf771add1c.PNG)

**Desktop**
 - Hệ điều hành: Windows 10 
 - Trình duyệt: Chrome 77
 - Phiên bản web: 0.5.2

**Comment by belivipro9x99** [comment]
Xin chào,

Cảm ơn bạn đã báo cáo! Lỗi đã được ghi nhận và sẽ được sửa trong thời gian sớm nhất!

**Comment by belivipro9x99** [comment]
Đã fix tại commit 647d2cf990028941d638dbfb2ad0516de92c7cd7
