### ISSUE TITLE
Tăng thời gian tự update bảng rank để giảm dung lượng web sử dụng

### ISSUE THREAD

**Issue by snowynguyen** [belivipro9x99/themis-web-interface#32]
**Mô tả**

Khi sử dụng web bằng kết nối 3G có tính phí trên lưu lượng sử dụng, việc bảng rank tự động update với tần suất khá cao gây rất tốn dung lượng. Cụ thể nếu chỉ mở trang web và không có hoạt động nào khác (không bấm F5, không submit bài, không mở trang web nào khác...) trong 8 tiếng liên tục sẽ tốn khoảng 800MB dung lượng (với setup thời gian làm mới = 10 giây).

**Giải pháp đề xuất**

Có thể có nhiều giải pháp, mình đề xuất 1 trong 3 giải pháp sau:
- Cho phép chỉnh thời gian làm mới lên cao hơn (tăng max bound lên 1-2 phút hoặc cao hơn) 
- Thêm button cho phép tắt hẳn việc tự update dữ liệu (và 1 button để làm mới bằng tay) 
- Tách hẳn bảng rank ra một webpage khác

**Giái pháp tạm thời**

Tạm thời mình lên server để lấy bài sau đó tắt trang web đi, sau đó khi nào cần submit mới mở trang web lại. Tuy nhiên cũng không khá hơn là bao do khi load mới, trang tải khá nhiều tài nguyên.

**Comment by belivipro9x99** [comment]
Chào bạn,

### Về vấn đề giảm tần suất update
Trong bảng cài đặt đã có một cài đặt cho phép thay đổi tần suất update của 2 bảng `rank` và logs`,
Bạn có thể tìm thấy cài đặt này tại **CÀI ĐẶT:Khác**
![image](https://user-images.githubusercontent.com/19252372/68545182-36401500-03fd-11ea-8609-aae68ac0a7db.png)
![image](https://user-images.githubusercontent.com/19252372/68545191-41934080-03fd-11ea-9107-72879930e966.png)

### Về vấn đề làm mới bằng tay
Tại mỗi bảng đã có sẵn một nút làm mới nhỏ nằm ở trên phải. Bạn có thể dùng nút này để cập nhật lại dữ liệu
![image](https://user-images.githubusercontent.com/19252372/68545239-bc5c5b80-03fd-11ea-934b-e55b56c60dc4.png)

### Về vấn đề tắt hẳn tự động update dữ liệu
Cảm ơn bạn đã góp ý! Mình sẽ thêm cài đặt này tại bản cập nhật tới!

### Về vấn đề thêm một trang Xếp Hạng riêng
Cảm ơn bạn đã góp ý! Bảng xếp hạng sẽ được tách sang một trang khác trong bản cập nhật tới! 😁

**Comment by belivipro9x99** [comment]
* Đã tăng giới hạn của thời gian làm mới tại commit 978730d7412af2e48eec406e69022a90aa72202e
![image](https://user-images.githubusercontent.com/19252372/68546688-c9804700-040b-11ea-94c4-a1d53c5d1ee4.png)

* Đã thêm cài đặt **Tự động cập nhật Xếp Hạng và Nhật Ký** tại commit 2cf5b7228794af8eeedc72c7a9193b2f7a6999ad
![image](https://user-images.githubusercontent.com/19252372/68546687-bff6df00-040b-11ea-8eca-26c24868695e.png)

* Đã thay đổi thời gian cache các file tĩnh lên `1 tuần` *(bao gồm `sounds`, `fonts` và `img`)* tại commit d2472b55ddcb113972b9713ea6b2ad8cf7bf345a
Sau thay đổi này, lần đầu tải trang sẽ tốn **5.55 MB**, các lần sau tải trang chỉ còn tốn **465 KB**!

Trang xếp hạng riêng sẽ được thêm tại bản cập nhật `v0.5.4`.
