### ISSUE TITLE
Token please

### ISSUE THREAD

**Issue by tacongnam** [belivipro9x99/themis-web-interface#37]
Bạn cho mình hỏi lỗi này là gì với cách fix như thế nào ạ? Cảm ơn bạn.
![image](https://user-images.githubusercontent.com/49036956/71967745-59891400-3236-11ea-827f-223e2d05321a.png)

**Comment by belivipro9x99** [comment]
Chào bạn,

Có thể mã nguồn đã bị thay đổi dẫn đến `API_TOKEN` tại [`index.php:869`](https://github.com/belivipro9x99/themis-web-interface/blob/4f6eed42ab250eddc83984bec86e690d12ebd90d/index.php#L869) bị mất hoặc bị trống, khiến việc request tới API `/api/logs` bị từ chối do thiếu *token*

Mong bạn thử lại với mã nguồn gốc tại branch **master** hoặc đính kèm thêm Console Logs [[?](https://support.shortpoint.com/support/solutions/articles/1000222881-save-google-chrome-browser-s-console-file)] để mình có thể xác định được lỗi

Nếu có bất kỳ tính năng nào bạn muốn có trong hệ thống, bạn luôn có thể góp ý tại [đây](https://github.com/belivipro9x99/themis-web-interface/issues/new/choose)!
