### ISSUE TITLE
File log bất đồng bộ, bài chấm trên themis rồi nhưng không hiện kết quả

### ISSUE THREAD

**Issue by snowynguyen** [belivipro9x99/themis-web-interface#38]
**Mô tả lỗi**
Như tiêu đề

**Để gây ra lỗi**
Các bước thực hiện để gây ra lỗi:
1. Dùng 2 máy khác nhau đăng nhập vào 2 tài khoản khác nhau, nộp cùng một bài vào cùng một thời điểm (giả sử tài khoản A được Themis chấm trước tài khoản B)
2. Tài khoản A nhận được file Log như bình thường, tài khoản B hiển thị trạng thái "Đang chấm" dù cho Themis đã chấm xong (Standing không hiện file log của B) 
3. Tải khoản B nộp lại bài đó. Khi bài nộp lại của tài khoản B có trạng thái "Đang chấm" thì file log tương ứng bài nộp _trước_ hiện lên standing. Khi Themis chấm xong bài nộp lại này thì thấy ở web, trạng thái bài nộp lại vẫn là "Đang chấm", file log của bài nộp trước đó biến mất khỏi standing.

**Hành vi dự kiến**
File log được đồng bộ hoá đúng đắn trên web chứ không bị "dồn"

**Desktop**
 - Hệ điều hành: Win 10 
 - Trình duyệt: Chrome 79
 - Phiên bản: v0.5.3.1 rev1

**Comment by belivipro9x99** [comment]
Cảm ơn bạn đã báo cáo lỗi! Hiện mình đang tiến hành điều tra nguyên nhân

**Comment by belivipro9x99** [comment]
Sau khi thử lại một số lần thì mình không thể tạo lại lỗi mà bạn đã nâu ở trên. ([Video](https://drive.google.com/file/d/1hwmQxWcVOUfGKA-QIzhmAjeV5EBz-qtA/view?usp=sharing))

Bạn hãy thử cập nhật **Themis** lên phiên bản mới nhất hoặc thử lại bằng mã nguồn tại branch `indev`. Nếu lỗi vẫn tiếp diễn, bạn hãy quay lại màn hình khi lỗi sảy ra (*quay với thư mục `Logs` được mở*) và đính kèm tại Issue này hoặc liên hệ mình qua Discord (`Belikhun#4688`) hoặc Messenger để có thể hỗ trợ tiếp

Issue này sẽ được tự động đóng sau 12 tiếng nếu không có hoạt động nào.

**Comment by snowynguyen** [comment]
Chào bạn, 

Mình gửi bạn video tái lập lỗi
https://drive.google.com/open?id=1M73ynmncyUj7oTCOTbEuC7l6-GMtxGW9

Hi vọng bạn xem qua 👍

**Comment by belivipro9x99** [comment]
Cảm ơn bạn!

Hiện mình đang tiếp tục điều tra nguyên nhân lỗi, mình sẽ thông tin lại với bạn sau.

**Comment by belivipro9x99** [comment]
Hiện tại mình chưa thể tìm ra được nguyên nhân do chưa tái hiện lại được lỗi. Mình có một số câu hỏi cần được bạn giải đáp:
* Source Code đã bị chỉnh sửa chưa?
* Phiên bản trình chấm Themis hiện lại là gì?
* Bạn đã gặp lỗi này ở những phiên bản trước chưa?

Nếu có thể, mong bạn hãy liên hệ với mình qua Discord (`Belikhun#4688`) hoặc [Messenger](https://m.me/belivipro9x99) để mình có thể hỗ trợ tiếp!

**Comment by snowynguyen** [comment]
1. Source code thì mình không biết bạn nói về source của bài làm hay source của web. Nhung cả 2 đều không bị chỉnh sửa nhé.
2. Version Themis: 1.9.8.2806
3. Thi thoảng có gặp nha bạn. 
Facebook của mình là https://www.facebook.com/namnnj, mình đã gửi lmkb cho bạn nhé

**Comment by belivipro9x99** [comment]
User Error. Closing this Issue
