### ISSUE TITLE
Các bài có cùng tên bị hiển thị thành nhiều cột trên bảng rank

### ISSUE THREAD

**Issue by snowynguyen** [belivipro9x99/themis-web-interface#39]
**Mô tả lỗi**
Bài nộp cho cùng một bài tập nhưng cách đặt tên in hoa / thường khác nhau được đưa thành nhiều cột khác nhau

**Để gây ra lỗi**
Các bước thực hiện để gây ra lỗi:
Giả sử trên server được setup chấm bài MATRIX
1. Thiết đặt **tắt** tùy chọn "Các bài nộp phải có trên danh sách đề"
2. Thí sinh A nộp file matrix.cpp
3. Thí sinh B nộp file MATRIX.cpp 
4. Kết quả chấm bài được format trên 2 cột (xem hình vẽ) 

**Hành vi dự kiến**
Theo quy cách đặt tên chuẩn thì các tên file là case-insensitive nên tên bài không nên phân biệt hoa thường.

**Ảnh chụp màn hình**
![image](https://user-images.githubusercontent.com/30857393/74001101-e261af80-499c-11ea-9cf0-d7aeb09e7797.png)

**Desktop (không yêu cầu):**
 - Hệ điều hành: Windows 7 
 - Trình duyệt: Chrome 79
 - Phiên bản: v0.5.3.1 rev1

**Comment by belivipro9x99** [comment]
Chào bạn,

Mong bạn kiểm tra lại tên bài `MATRIX` trong trình chấm Themis là chữ hoa hay chữ thường. Lỗi này đã được sửa tại commit a147a5cc591356f2f6fb4c0bb9a3a4271288390a trong phiên bản `0.5.3-rev1`.

**Comment by snowynguyen** [comment]
> Chào bạn,
> 
> Mong bạn kiểm tra lại tên bài `MATRIX` trong trình chấm Themis là chữ hoa hay chữ thường. Lỗi này đã được sửa tại commit [a147a5c](https://github.com/belivipro9x99/themis-web-interface/commit/a147a5cc591356f2f6fb4c0bb9a3a4271288390a) trong phiên bản `0.5.3-rev1`.

Trong themis đề là chữ thường bạn nhé. Không biết đây có phải là intended behaviour không bạn?

**Comment by belivipro9x99** [comment]
Không, khi tắt cài đặt `Các bài nộp lên phải có trong danh sách đề` thì toàn bộ bài nộp lên phải được chuyển thành **CHỮ HOA** để đảm bảo không có trường hợp 1 bài có nhiều cột như hình ở trên.

Bạn hãy thử tạm thời tắt trình chấm Themis, nộp một bài lên và check xem trong thư mục lưu bài tải lên tên của tệp đấy đã được chuyển thành chữ hoa chưa. Nếu tên đã là chữ hoa thì bạn kiểm tra lại ở trình chấm Themis nha

**Comment by snowynguyen** [comment]
Ok bạn. Nói chung vẫn tốt hơn nếu có workaround ở phía server luôn, nhưng mình cũng ghi nhận đây là intended behaviour và hài lòng với solution bạn đưa ra Việc _thí sinh tự đổi tên file nộp của mình thành chữ hoa_ đã fix được vấn đề.

**Comment by belivipro9x99** [comment]
Không bạn, thí sinh không cần phải đổi tên tệp thành chữ hoa trước khi nộp mà sau khi nộp tệp đấy sẽ được tự động chuyển thành chữ hoa ở commit a147a5cc591356f2f6fb4c0bb9a3a4271288390a. Mình nghĩ là do trình chấm Themis lại xuất tên file log ra thành chữ thường nên mới có hiện tượng chia cột đấy
