### ISSUE TITLE
Thêm tính năng ẩn đề bài

### ISSUE THREAD

**Issue by Noboroto** [belivipro9x99/themis-web-interface#40]
**Vấn đề**
Server luôn chứa rất nhiều đề bài để học sinh có thể tự nộp và sửa lỗi. Chính vì vậy khi muốn tổ chứ 1 kỳ thi thì phải xoá lần lượt từng đề cũ hoặc sao lưu lại các đề không cần thiết một cách thủ công.

**Tính năng mong muốn**
Phần mềm nên có thêm tính năng ẩn đề bài không cần thiết để có thể giữ lại nguồn đề, khi cần thfi có thể mở ra nhanh ngay trên giao diện

**Comment by belivipro9x99** [comment]
Cảm ơn bạn đã góp ý!

Ý tưởng này khá là hay và sẽ có trong bản cập nhật `v0.6.0` sắp tới!

**Comment by belivipro9x99** [comment]
Added in commit ad05c23252fdb995f1555c2eec6c317b6554f528
