### ISSUE TITLE
Làm sao để ẩn bớt cột điểm trên bảng rank

### ISSUE THREAD

**Issue by JackSmart1234** [belivipro9x99/themis-web-interface#42]
bảng rank có những bài đã làm xong rồi nên bây h minh muốn ẩn hoặc bỏ đi thì làm như thế nào?

**Comment by belivipro9x99** [comment]
Chào bạn,

Với phiên bản hiện tại thì không thể ẩn cột của bảng xếp hạng trừ khi bạn xóa từng tệp nhật kí của cột.

Mình sẽ tiếp thu ý kiến này và sẽ thêm tính năng ẩn cột khi đề bài liên quan đến cột bị ẩn đi trong bản cập nhật `v0.6.0` sắp tới! (liên quan đến #40)

**Comment by JackSmart1234** [comment]
tệp nhật ký được để ở đâu vậy bạn

**Comment by belivipro9x99** [comment]
Tệp nhật ký được để ở thư mục `Logs` bên trong thư mục lưu bài làm nha bạn

**Comment by JackSmart1234** [comment]
cảm ơn bạn

**Comment by belivipro9x99** [comment]
Wait a sec...

**Comment by belivipro9x99** [comment]
+ Đã thêm tính năng `ẩn điểm của đề bài bị tắt` tại commit a551a61bb70338fdb5b026719c155c2be5a4c961
+ Đã thêm tính năng `thu gọn cột của bảng xếp hạng` tại commit b0fde080970e207becf3d372ff50351735095e6e

![image](https://user-images.githubusercontent.com/19252372/75544134-ec377980-5a55-11ea-915f-1615f0fc9c88.png)
