### ISSUE TITLE
Không thể điều hướng (bằng thanh trượt và bàn phím) để đọc đề

### ISSUE THREAD

**Issue by Noboroto** [belivipro9x99/themis-web-interface#46]
**Mô tả lỗi**
Nếu như số lượng đề quá lớn thì để đọc được đề ở những vị trí cuối thì thí sinh/admin phải thu nhỏ cửa số mà không có thanh trượt hay dùng bàn phím để đến đề cần đọc

**Phiên bản:**
- Themis Web Interface v0.6.0
 - Hệ điều hành: Windows 10 Pro 1909 build 18363.657
 - Trình duyệt: Microsoft Edge Chromium Version 80.0.361.62 (Official build) (64-bit)
và Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Thông tin thêm**
số lượng đề hiển thị ít
<img width="956" alt="2020-03-01" src="https://user-images.githubusercontent.com/48942146/75629235-be4b6400-5c12-11ea-82da-0649a58ce4b4.png">
số lượng đề đã bị thiếu ở hình trên
<img width="952" alt="2020-03-01 (1)" src="https://user-images.githubusercontent.com/48942146/75629221-a5db4980-5c12-11ea-8b20-2b32fe3ca279.png">

**Comment by belivipro9x99** [comment]
Cảm ơn bạn đã báo lỗi! Bản cập nhật sửa lỗi sẽ được ra trong thời gian sớm nhất!

**Comment by belivipro9x99** [comment]
Đã sửa tại commit a3bd9e6e2358dc3850fc82abf4ecb0f122622397
