### ISSUE TITLE
Lỗi hiển thị Nhật kí

### ISSUE THREAD

**Issue by abcltvp3000** [belivipro9x99/themis-web-interface#48]
**Mô tả lỗi**
Nhật kí hiển thị tràn xuống Bảng xếp hạng nếu có quá một số file logs nhất định nào đó

**Để gây ra lỗi**
Các bước thực hiện để gây ra lỗi:
1. Tắt tính năng "Các bài nộp lên phải có trong danh sách đề".
2. Tạo ra nhiều file logs.
3. Nhìn vào phần nhật kí và cuộn xuống.
4. Lỗi!!!

**Hành vi dự kiến**
x

**Ảnh chụp màn hình**
![image](https://user-images.githubusercontent.com/53158639/75943304-3c379580-5ec7-11ea-85e4-40730eb33a59.png)
![image](https://user-images.githubusercontent.com/53158639/75943329-46599400-5ec7-11ea-94a5-61ed428b5d4d.png)

**Phiên bản:**
 - Hệ điều hành: Windows 10 Pro 64bit
 - Trình duyệt: 
   + Microsoft Edge | 80.0.361.62
   + Google Chrome | 80.0.3987.132
 - Trình chấm: Themis v1.9.8 b.2806
 - Phiên bản trang web: Themis Web Interface v0.6.0-rev1

**Thông tin thêm**
x

**Comment by belivipro9x99** [comment]
Cảm ơn bạn đã báo cáo!

**Comment by belivipro9x99** [comment]
Đã fix tại commit bff1effa05a1ceb24b916f5466b3daeb0f08c264
