### ISSUE TITLE
Thêm tính năng cho trang web

### ISSUE THREAD

**Issue by abcltvp3000** [belivipro9x99/themis-web-interface#50]
**Ý kiến của mình:**
    + Hiện tại phần Scoreboard của trang web không hiển thị hết thí sinh, test, điểm tối đa của bài... khi chưa có file Logs.
    + ADMIN không thể biết thí sinh có online hay không.
    + Trang web nên có Announcement để thông báo những tin quan trong ngay trên trang web cho thí sinh.
    + Scoreboard sắp xếp vị trí của thí sinh theo điểm và thời gian nộp bài (trong 2 người có điểm như nhau, người nộp trước sẽ có thứ hạng cao hơn).

**Trên đây chỉ là một số góp ý để phát triển trang web. Mong bạn tiếp nhận và phát triển Project ngày càng hoàn thiện hơn!**

**Comment by belivipro9x99** [comment]
Cảm ơn bạn đã đóng góp ý kiến!

Mình thấy 3 tính năng này khá hợp lý và sẽ thêm những tính năng này trong bản cập nhật tiếp theo 😁

**Comment by dolam529** [comment]
Đc luôn ^^

Vào 22:41, Th 3, 10 thg 3, 2020 Belikhun <notifications@github.com> đã viết:

**Comment by abcltvp3000** [comment]
Cảm ơn bạn! :)

**Comment by belivipro9x99** [comment]
Resolved in commits d663855e7c019306343a42d4ae21dc0cf4f110a8, 60aa969329194324d0be281ae322a1fa9c2c1578, 095f62f611b12f440650e409f7ed8a5ff0321821 and 4703cf2370635e420c00bd26c407b2016b149d55
