### ISSUE TITLE
Giới hạn số lần nộp bài

### ISSUE THREAD

**Issue by Noboroto** [belivipro9x99/themis-web-interface#51]
Mong admin có thể thêm tính năng giới hạn số lần nộp bài cho 1 thí sinh/ bài/ kỳ thi
Cho mình hỏi thêm rằng có thể chấm bằng 2 máy khác nhau được không?

**Comment by belivipro9x99** [comment]
Cảm ơn bạn đã góp ý!

Giới hạn nộp cho từng bài sẽ được thêm vào bản cập nhật tiếp theo!

Về câu hỏi của bạn, bạn có thể cho máy thứ nhất chạy máy chủ và Themis bình thường và chia sẻ thư mục nộp bài, `Tasks` và `Contestants` trong mạng LAN (Windows có hỗ trợ chia sẻ thư mục và ổ đĩa trong mạng LAN, còn linux bạn nên dùng `samba`). Sau đó ở máy thứ 2 bạn chạy Themis và chọn các thư mục được chia sẻ từ máy thứ nhất tương ứng

Mình có vẽ nhanh 1 sơ đồ đơn giản giúp bạn dễ dàng hiểu hơn
![Group 13](https://user-images.githubusercontent.com/19252372/76585460-015ddf00-6511-11ea-8dd9-2c6a94917373.png)

**Comment by Noboroto** [comment]
À mình váo thêm một lỗi chính tả
https://github.com/belivipro9x99/themis-web-interface/blob/master/README.md#xem-thông-tin-kết-quả-chấm-đầy-đủ
Thay **Dao diện** thành **Giao diện**

**Comment by belivipro9x99** [comment]
😅

**Comment by belivipro9x99** [comment]
Resolved in commit 21c7cbfc2dc6fa1be3225268805053775d6b81ba
PS: Almost took me 1 year to resolve this issue 😥

**Comment by Noboroto** [comment]
Mình mà có time học thêm php là bay vô code phụ rồi 🥲
