### ISSUE TITLE
Lỗi UI: Button exit cửa sổ đề bài bị khuất

### ISSUE THREAD

**Issue by snowynguyen** [belivipro9x99/themis-web-interface#54]
**Mô tả lỗi**
Khi mở cửa sổ đề bài, nút thoát (X) ở góc trên bên phải bị khuất rất nhỏ, khó bấm

**Để gây ra lỗi**
Các bước thực hiện để gây ra lỗi:
1. Tạo đề bài theo format của server
2. Mở cửa số đề bài
3. Chú ý đến biểu tượng (X) để thoát cửa số. Biểu tượng rất nhỏ và bị khuất sau thanh đếm thời gian

**Ảnh chụp màn hình**
![image](https://user-images.githubusercontent.com/30857393/77254559-4f52af80-6c94-11ea-8e05-b287df511dae.png)

**Phiên bản:**
 - Hệ điều hành: Windows 10
 - Trình duyệt: Chrome
 - Trình chấm: Themis

**Comment by belivipro9x99** [comment]
đã fix tại commit 57d2b193d33d99f1b77779a0d7890ea186f64601
