### ISSUE TITLE
Force logout khi mật khẩu bị admin thay đổi

### ISSUE THREAD

**Issue by snowynguyen** [belivipro9x99/themis-web-interface#56]
Hi bạn, mình có 1 đề xuất như sau:

Khi mình thay đổi mật khẩu của một tài khoản bất kì lúc user vẫn còn đăng nhập thì user đó không bị logout hay gì cả. Mình cảm thấy để đảm bảo vấn đề bảo mật thì khi mật khẩu bị đổi thì cần force logout tài khoản của các máy đang đăng nhập.

Ngắn gọn thế thôi hihi, rất hi vọng được bạn phản hồi :D

**Comment by belivipro9x99** [comment]
Will Do!

**Comment by belivipro9x99** [comment]
Resolved in commit 2edc7e1ce03433a011d8afce96b855d9d8874451
