### ISSUE TITLE
Khi đưa lên hosting thì cấu hình thế nào

### ISSUE THREAD

**Issue by phimsn** [belivipro9x99/themis-web-interface#57]
Chào ad!
Khi đưa lên hosting thì mình không biết cấu hình thế nào để có thể upload file lên được. mong ad giúp đỡ

**Comment by belivipro9x99** [comment]
Chào Bạn,
Bạn có thể cho mình biết bạn đang muốn đưa lên hosting nào không?

Vào Th 6, 12 thg 6, 2020 vào lúc 16:00 yonashi <notifications@github.com>
đã viết:

**Comment by belivipro9x99** [comment]
Đóng vì không có hoạt động
