### ISSUE TITLE
Làm sao để chỉnh sửa problem trên web ạ

### ISSUE THREAD

**Issue by dangdoanninh** [belivipro9x99/themis-web-interface#60]
mình thấy trong "/data/problems/problem.php " có vẻ là dùng để chỉnh sửa các bài tập + test mà bị lỗi 403 khi truy cập, mong được bạn hỗ trợ ạ

**Comment by belivipro9x99** [comment]
Chào bạn,

Trong phần **Admin** của bảng cài đặt có một tùy chọn là *Chỉnh sửa đề bài*, bạn có thể quản lý đề bài tại đó
![image](https://user-images.githubusercontent.com/19252372/94438752-bd3edd00-01c9-11eb-9d7e-5b3ceae04c1f.png)

Để sử dụng tính năng này thì tài khoản bạn đang đăng nhập phải có quyền quản trị. (Bạn có thể chỉnh bất kì tài khoản nào thành quản trị bằng cách chỉnh sửa `id` của tài khoản đó thành `admin`)

**Comment by dangdoanninh** [comment]
![image](https://user-images.githubusercontent.com/72019710/94440930-5d960100-01cc-11eb-9939-87df175470b9.png)
![image](https://user-images.githubusercontent.com/72019710/94440971-671f6900-01cc-11eb-9f86-1ae8cccd92b3.png)
bảng cài đặt đấy ở đâu vậy ạ, mình tìm mãi không thấy ở đâu ạ

**Comment by belivipro9x99** [comment]
Bạn lăn chuột xuống trong bảng Cài Đặt là sẽ thấy
