### ISSUE TITLE
Tính năng sắp xếp bài theo tên thay vì theo ID

### ISSUE THREAD

**Issue by AnoTherK-ATK** [belivipro9x99/themis-web-interface#61]
Em không biết rằng có cách nào để sắp xếp đề bài theo tên thay vì theo ID hay không
![image](https://user-images.githubusercontent.com/16263124/94933003-ffcb2700-04f3-11eb-929d-0bba3e9dc31d.png)
vì khi em tính đưa thêm các bài mà sắp xếp theo ID thì nó dính chặt rồi đổi thì phải đổi lại cả đề

**Comment by belivipro9x99** [comment]
Hiện tại thì không có cách nào để sắp xếp đề theo tên. Mình sẽ để sắp xếp theo tên thành mặc định ở bản cập nhật tiếp theo!

**Comment by dangdoanninh** [comment]
ad ơi mình nghĩ nếu có thêm hệ thống đếm thời gian làm bài để làm tiêu chí phụ khi xếp hạng mà có điểm bằng nhau ấy ạ

**Comment by belivipro9x99** [comment]
Hiện trong bản thử nghiệm mình đã thêm một hệ thống điểm có tên là `Submission Point`, trong đó sẽ lấy ba tiêu chí là *thời gian nộp trong kì thi*, *số lần chấm lại* và *thứ hạng nộp*. Hệ thống điểm SP này luôn đảm bảo rằng điểm của mỗi bài sẽ khác nhau.

![image](https://user-images.githubusercontent.com/19252372/85224625-c3b50000-b3f5-11ea-9e20-266e76eaa2c0.png)

Hiện mình đã sắp hoàn thiện và sẽ tung ra bản thử nghiệm đầu tiên của phiên bản `1.0.0`, mong bạn có thể tham gia thử nghiệm hệ thống và góp ý!

**Comment by belivipro9x99** [comment]
Resolved in commit d2baea9753025f988a798f5d55e40addfa26d8d2
