### ISSUE TITLE
Lỗi nộp bài báo không có tên đề

### ISSUE THREAD

**Issue by QuangIT2309** [belivipro9x99/themis-web-interface#62]
**Mô tả lỗi**
ở chế độ đăng nhập, mình nộp bài thì báo lỗi "Không có đề cho bài này" mặc dù đã có đề

**Để gây ra lỗi**
Các bước thực hiện để gây ra lỗi:
1. Đi tới 'Đăng nhập"
2. Nhấn vào '"nộp bài"
3. Web hiển thị "KHÔNG CÓ ĐỀ CHO BÀI NÀY"
4. Lỗi!!!

**Hành vi dự kiến**
MÌNH COPY BỘ WEB THEMIS NÀY SANG MÁY KHÁC, CÀI LẠI IP TRÊN MODEM ĐỂ THIẾT LẬP SERVER, CHẠY VÀ BÁO LỖI NHƯ TRÊN

**Ảnh chụp màn hình**
![image](https://user-images.githubusercontent.com/39910902/124227587-21197c00-db35-11eb-84ac-11670084e5aa.png)

**Phiên bản:**
 - Hệ điều hành:  Windows
 - Trình duyệt:  Chrome, 
 - Trình chấm: [vd: Themis v1.9.8 b.2806]

**Thông tin thêm**
Thêm bất kỳ thông tin nào liên quan đến lỗi tại đây.

**Comment by QuangIT2309** [comment]
Một số bài thì nộp được, một số bài thì không được

**Comment by belivipro9x99** [comment]
Bạn có thể test lại lỗi này trên bản `1.1.0-beta` được không? Vì lỗi này có thể mình đã fix rùi...
