### ISSUE TITLE
🍓 Lỗi khởi tạo trang khi chạy máy chủ trên cổng khác

### ISSUE THREAD

**Issue by mystar0806** [belivipro9x99/themis-web-interface#63]
Khi mình đổi port 80 -> 81 của uniserver thì nó báo lỗi như hình. Mong admin hướng dẫn khắc phục, cảm ơn nhiều!
![Capture](https://user-images.githubusercontent.com/87182068/125066602-61e93600-e0dd-11eb-894e-17591643dbcf.JPG)

**Comment by belivipro9x99** [comment]
Cảm ơn bạn đã báo lỗi! Lỗi này đã được fix tại commit 63739e362817b6da0acfe22739aa597d80b96f64
Trong lúc chờ mình ra phiên bản `1.2.0-beta`, bạn có thể sửa lỗi này ở bản `1.1.0-beta` bằng cách tải về file [`smenu.js`](https://raw.githubusercontent.com/belivipro9x99/themis-web-interface/indev/assets/js/smenu.js) và thay thế tệp `/assets/js/smenu.js`

**Comment by mystar0806** [comment]
cảm ơn admin
