### ISSUE TITLE
Bật/Tắt bảng xếp hạng đối với khách

### ISSUE THREAD

**Issue by mystar0806** [belivipro9x99/themis-web-interface#67]
**Câu hỏi**
Mình muốn bật / tắt  bảng xếp hạng đối với khách thì phải làm sao?

**Comment by belivipro9x99** [comment]
Hiện tại twi chưa có tính năng này. Tính năng `Bắt buộc đăng nhập khi vào trang` sẽ được thêm vào bản thử nghiệm tiếp theo nha.
